### PR TITLE
Do not omit from medial axis touching bisectors for narrow angles

### PR DESCRIPTION
**Pull request by strk**
With this change, "tails" of narrow polygons defined with just 3 points (rather than a smooth curve) would be retained in output. The condition is that the angle between edges have to be <= 45 degrees for non-inner (touching) bisectors to be retained. The value is currently hard-coded.

I'll add examples to show why this is useful, possibly turned into testcases.

### CODE REVIEW

**Comment by strk** [comment]
Here's an example input that looks better with the patch.

Before:

delta

After:

deltagood

**Comment by strk** [comment]
check is failing because the medial axis of a triangle is not empty anymore now... looking at what a good fix for this would be.

**Comment by strk** [comment]
The failing test can now actually serve as a test for the new feature, as it's a triangle with two 45 degrees angles so now results in a medial axis composed by two edges bisecting those two angles

**Comment by strk** [comment]
@vmora  you can see here what I'm doing with angles :)
I think this can be merged, but if a second pair of eyes can review that'd be nice

**Comment by vmora** [comment]
+1 for me.

**Comment by strk** [comment]
Pushed as commit d80ad19a35cf44ebac574f9085ff8e5594b90795

**Comment by strk** [comment]
On Mon, Nov 16, 2015 at 12:53:14PM -0800, Ian Reese wrote:
> Hi Strk,  Could you possibly put strk:missingTail back up?

Done, but why did you need this ?
The pull was merged in the master branch

**Comment by IReese** [comment]
Cheers Sandro,

I realized that a bit later and feel a little foolish for asking now.   I am installing it today and will hopefully have it up and running soon.  Thanks for putting it back up although I guess I didn’t need it.

Take care,

Ian

**Pull request closed without merging**
