### PR TITLE
Fix StraightSkeleton crash reported in #111

### PR DESCRIPTION
**Pull request by strk**
No test included in this commit.

### CODE REVIEW

**Comment by strk** [comment]
I'm not sure how should this be put under testing, as while an exception is _far_ better than a crash, there's still no result obtained...

**Comment by vmora** [comment]
Not sure I get the testing problem: if the test crash it fails, if the test should throw an doesn't or throws when it should not, the test fails...

**Comment by strk** [comment]
I was hoping to use existing infrastructure, rather than writing
a new test from scratch.

Maybe allowing to write some symbols in data/StraightSkeletonTest.txt
would work, for example to expect a NULL. But I'd rather not put
under regression testing such a poor expectancy, so maybe we should
allow to use a symbol to specify "good as long as it does not crash".

**Comment by strk** [comment]
Alright the test is now in place. Exception message will be written in the "expectedWKT" field for now.
Once travis is green this can be merged

**Comment by strk** [comment]
vmora it could be I missed something, but if I try to change expected results I do get a failure already

**Pull request merged**
