### PR TITLE
Issue #130: Add 3D linear referencing

### PR DESCRIPTION
**Pull request by danielcu888**
Implemented functionality requested by Issue #130 to retrieve a segment of a specified (2D or 3D) LineString, between the specified fractional distances from the start of the specified LineString.

### CODE REVIEW

**Comment by lbartoletti** [comment]
Thanks Daniel. We'll review your PR very soon. Can you delete the DS-store files and add this entry to the gitignore please?

**Comment by danielcu888** [comment]
@lbartoletti absolutely, apologies for that.

**Comment by danielcu888** [comment]
@lbartoletti thanks for the approval. Can it now be merged?

**Comment by lbartoletti** [comment]
Thanks @danielcu888! Works much appreciated.

Only one question, what do you think about rename LineSegment to LineSubstring?

**Comment by danielcu888** [comment]
@lbartoletti yes, LineSubstring does sound better, I'll make the change.

**Comment by danielcu888** [comment]
@lbartoletti I have now made the change requested.

**Comment by lbartoletti** [comment]
Thank you!

**Pull request merged**
