### PR TITLE
Improve straight skeleton robustness

### LINKED ISSUE #89: Robustness issue with StraightSkeleton and inexact construction kernel
Looking at the StraightSkeleton for the input reported in ticket #80 reveals a robustness issue that results in a piece of skeleton falling outside the input polygon, see:

skeleton_inexact_kernel

The artifact goes away if the input polygon is first translated to have 0,0 as its lowest-left point and the output skeleton is translated back to its original position, see:

skeleton_inexact_kernel_shifted

The skeleton computed with "extact construction" kernel is otherwise visually equal to the one computed with the improved robusness (shifting). Running the translation doesn't significantly affect performances.

Maybe this issue should be reported upstream to CGAL..

### PR DESCRIPTION
**Pull request by strk**
This is done by shifting data near the origin
while computing the skeleton.

Fixes #89

### CODE REVIEW

**Comment by strk** [comment]
I'm looking at adding a testcase for this, meanwhile if you see an opportunity to avoid a copy, that'd be nice (but performance isn't bad as it is)

**Comment by strk** [comment]
Writing the testcase I hit another bug, making "Covers" return true when instead should return false ...
See #93

**Comment by strk** [comment]
So #93 was finally found to be an invalid bug. But I'm still having problems reproducing the robustness issue when reading the polygon from WKT, as it slightly moves vertices to not represent a problem anymore.

**Comment by Remi-C** [comment]
If I remember well, WKT limits the precision.
WKB on the opposite is more precise (about 2 digits more).

Maybe you should test using wkb as input, and not wkt.

Cheers,
Rémi-C

2015-06-17 11:10 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Right, but I can't find a way for SFCGAL to take WKB input.

**Comment by vmora** [comment]
This may be worth an enhancement ticket

**Comment by strk** [comment]
Filed: #94

**Comment by strk** [comment]
Pushed as c9e3cffe918c7798440cf4cd3e2a6e9c4c8554d8 -- testcase will need to wait (will file another ticket)

**Pull request closed without merging**
