### PR TITLE
Use inexact construction kernel for straight skeleton

### LINKED ISSUE #80: Slow StraightSkeleton computation with a 420 vertices single-ring polygon
See https://trac.osgeo.org/postgis/ticket/3168

### PR DESCRIPTION
**Pull request by strk**
Fixes #80
Includes benchmark test.

### CODE REVIEW

**Comment by strk** [comment]
NOTE: includes benchark of #82, which I'm closing

**Comment by strk** [comment]
Note: with this change, the benchmark runs in 0.36 seconds rather than 16.2 seconds on my machine.
Benchmark:
```
 ./test/bench/bench-SFCGAL --log_level=test_suite  --run_test=SFCGAL_BenchStraightSkeleton/testPolygon80
```

**Comment by strk** [comment]
I'm refactoring it to also add same treatment to multipolygon input

**Comment by strk** [comment]
Ready to merge as far as I can tell. Will base next one (approximateMedialAxis) on this branch.
\cc @vmora

**Comment by vmora** [comment]
@strk the style test fails (you can autofix by running `./script/test-style-SFCGAL.sh --fix` from top level directory)

**Comment by strk** [comment]
By running that command I get: 298 files changed, 47374 deletions(-)
When we tried to use astyle for PostGIS we gave up shortly after finding
out different versions gave different results.

I'm using Artistic Style Version 2.03

**Comment by strk** [comment]
See also #78

**Pull request merged**
